Finish version Full Chart Page
Kacper-Grzyb/BrickedUp pull request #15
Opened 2024-11-23 18:34 UTC by Leonardo-Gianola

This is the final version of the full graph page, I created a controller, then made changes to css, blade.php, js and web.php, changes to docker-compose.yml can be removed.

2024-11-24 17:40 UTC, Kacper-Grzyb requested changes
Consider the feedback for set theme colours, and please update docker-compose.yml and double check web.php routes

2024-11-24 17:40 UTC, Kacper-Grzyb commented on BrickedUp/docker-compose.yml
Please update to the new version of the docker-compose.yml file. The current won't run, you can get the new one from the main branch

2024-11-24 17:40 UTC, Kacper-Grzyb commented on BrickedUp/public/js/full-graph.js
> +            return themeColors[themeId] || "#FFFFFF"; // Default to white if theme not found
Maybe return a random color if the set theme was not found instead of just white. My reasoning for this is because didn't configure a lot of pre-set theme colors, so the user could end up seeing all white. Randomizing the color could add some differentiation. You could also do it in a way so that there is a max amount of themes you can add, and each addition gets its color based on the order, not exactly the theme itself. Also if you want to stick with each theme having it's designated colour, maybe consider adding it as a column to the database, or making a designated table

2024-11-24 17:40 UTC, Kacper-Grzyb commented on BrickedUp/public/js/full-graph.js
> +            return themeColors[themeId] || "#FFFFFF"; // Default to white if theme not found
Also I am not sure if this way of checking if the Dictionary has a key-value pair is correct, this may throw an exception. A more correct way of doing this would be to do something like themeColors.hasKey(themeId) or something along those lines, I don't remember the syntax for js

2024-11-24 17:40 UTC, Kacper-Grzyb commented on BrickedUp/routes/web.php
Also here please make sure the routes are up to date with main, since when I pulled I had to resolve some conflicts in my local branch and I'm not sure if the end product was as intended

2024-11-27 08:26 UTC, Leonardo-Gianola commented on BrickedUp/public/js/full-graph.js
> +            return themeColors[themeId] || "#FFFFFF"; // Default to white if theme not found
I put random color for all the sets theme

2024-11-27 09:42 UTC, Leonardo-Gianola commented on BrickedUp/public/js/full-graph.js
> +            return themeColors[themeId] || "#FFFFFF"; // Default to white if theme not found
I changed the way to this one: themeColors.hasOwnProperty(themeId). This the js sintax to check if a dictionary has a key-value pair

2024-11-27 09:54 UTC, Leonardo-Gianola commented
Ok hermano, hice todos los cambios en los colores, cambié el archivo docker-compose.yml al que está en principal y cambié las rutas web.php.

2024-11-30 20:58 UTC, Kacper-Grzyb approved these changes
Kurwa pollos hermanos i tak żeś wkleił stary docker-compose.yml, ale już podmieniłem na nowy i wszystko śmiga. Oprócz tego zaaktualizowałem kilka rzeczy na twojej  stronie po lewej gdzie wyświetlają się zestawy, tak żeby było widać rzeczywiście nazwe tematyki zestawu a nie tylko jej indeks. Poza tym ustawione zestawy nie zapisują się między ekranami, ale to już moge ogarnąć w swoim projekcie indywidualnym także nie będę więcej zmian requestował

2024-11-30 20:58 UTC, merged